/** @type {import('tailwindcss').Config} */
import containerQueries from "@tailwindcss/container-queries";
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";

export default {
  darkMode: "selector",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1rem",
        md: "1rem",
        lg: "1rem",
        xl: "1rem",
        "2xl": "3rem",
      },
    },
    extend: {
      spacing: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      height: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      minHeight: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      maxHeight: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      width: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      minWidth: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      maxWidth: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      size: {
        128: "32rem",
        144: "36rem",
        160: "40rem",
      },
      fontFamily: {
        body: ["Inter", "system-ui", "sans-serif"],
        heading: ["Open Sans", "system-ui", "sans-serif"],
      },
      colors: {
        primary: {
          50: "hsl(var(--color-primary-50) / <alpha-value>)",
          100: "hsl(var(--color-primary-100) / <alpha-value>)",
          200: "hsl(var(--color-primary-200) / <alpha-value>)",
          300: "hsl(var(--color-primary-300) / <alpha-value>)",
          400: "hsl(var(--color-primary-400) / <alpha-value>)",
          500: "hsl(var(--color-primary-500) / <alpha-value>)",
          600: "hsl(var(--color-primary-600) / <alpha-value>)",
          700: "hsl(var(--color-primary-700) / <alpha-value>)",
          800: "hsl(var(--color-primary-800) / <alpha-value>)",
          900: "hsl(var(--color-primary-900) / <alpha-value>)",
          950: "hsl(var(--color-primary-950) / <alpha-value>)",
        },
        secondary: {
          50: "hsl(var(--color-secondary-50) / <alpha-value>)",
          100: "hsl(var(--color-secondary-100) / <alpha-value>)",
          200: "hsl(var(--color-secondary-200) / <alpha-value>)",
          300: "hsl(var(--color-secondary-300) / <alpha-value>)",
          400: "hsl(var(--color-secondary-400) / <alpha-value>)",
          500: "hsl(var(--color-secondary-500) / <alpha-value>)",
          600: "hsl(var(--color-secondary-600) / <alpha-value>)",
          700: "hsl(var(--color-secondary-700) / <alpha-value>)",
          800: "hsl(var(--color-secondary-800) / <alpha-value>)",
          900: "hsl(var(--color-secondary-900) / <alpha-value>)",
          950: "hsl(var(--color-secondary-950) / <alpha-value>)",
        },
        accent: {
          50: "hsl(var(--color-accent-50) / <alpha-value>)",
          100: "hsl(var(--color-accent-100) / <alpha-value>)",
          200: "hsl(var(--color-accent-200) / <alpha-value>)",
          300: "hsl(var(--color-accent-300) / <alpha-value>)",
          400: "hsl(var(--color-accent-400) / <alpha-value>)",
          500: "hsl(var(--color-accent-500) / <alpha-value>)",
          600: "hsl(var(--color-accent-600) / <alpha-value>)",
          700: "hsl(var(--color-accent-700) / <alpha-value>)",
          800: "hsl(var(--color-accent-800) / <alpha-value>)",
          900: "hsl(var(--color-accent-900) / <alpha-value>)",
          950: "hsl(var(--color-accent-950) / <alpha-value>)",
        },
        success: {
          50: "hsl(var(--color-success-50) / <alpha-value>)",
          100: "hsl(var(--color-success-100) / <alpha-value>)",
          200: "hsl(var(--color-success-200) / <alpha-value>)",
          300: "hsl(var(--color-success-300) / <alpha-value>)",
          400: "hsl(var(--color-success-400) / <alpha-value>)",
          500: "hsl(var(--color-success-500) / <alpha-value>)",
          600: "hsl(var(--color-success-600) / <alpha-value>)",
          700: "hsl(var(--color-success-700) / <alpha-value>)",
          800: "hsl(var(--color-success-800) / <alpha-value>)",
          900: "hsl(var(--color-success-900) / <alpha-value>)",
          950: "hsl(var(--color-success-950) / <alpha-value>)",
        },
        warning: {
          50: "hsl(var(--color-warning-50) / <alpha-value>)",
          100: "hsl(var(--color-warning-100) / <alpha-value>)",
          200: "hsl(var(--color-warning-200) / <alpha-value>)",
          300: "hsl(var(--color-warning-300) / <alpha-value>)",
          400: "hsl(var(--color-warning-400) / <alpha-value>)",
          500: "hsl(var(--color-warning-500) / <alpha-value>)",
          600: "hsl(var(--color-warning-600) / <alpha-value>)",
          700: "hsl(var(--color-warning-700) / <alpha-value>)",
          800: "hsl(var(--color-warning-800) / <alpha-value>)",
          900: "hsl(var(--color-warning-900) / <alpha-value>)",
          950: "hsl(var(--color-warning-950) / <alpha-value>)",
        },
        error: {
          50: "hsl(var(--color-error-50) / <alpha-value>)",
          100: "hsl(var(--color-error-100) / <alpha-value>)",
          200: "hsl(var(--color-error-200) / <alpha-value>)",
          300: "hsl(var(--color-error-300) / <alpha-value>)",
          400: "hsl(var(--color-error-400) / <alpha-value>)",
          500: "hsl(var(--color-error-500) / <alpha-value>)",
          600: "hsl(var(--color-error-600) / <alpha-value>)",
          700: "hsl(var(--color-error-700) / <alpha-value>)",
          800: "hsl(var(--color-error-800) / <alpha-value>)",
          900: "hsl(var(--color-error-900) / <alpha-value>)",
          950: "hsl(var(--color-error-950) / <alpha-value>)",
        },

        base: {
          50: "hsl(var(--color-base-background-50) / <alpha-value>)",
          100: "hsl(var(--color-base-background-100) / <alpha-value>)",
          200: "hsl(var(--color-base-background-200) / <alpha-value>)",
          300: "hsl(var(--color-base-background-300) / <alpha-value>)",
          400: "hsl(var(--color-base-background-400) / <alpha-value>)",
          500: "hsl(var(--color-base-background-500) / <alpha-value>)",
          600: "hsl(var(--color-base-background-600) / <alpha-value>)",
          700: "hsl(var(--color-base-background-700) / <alpha-value>)",
          800: "hsl(var(--color-base-background-800) / <alpha-value>)",
          900: "hsl(var(--color-base-background-900) / <alpha-value>)",
          950: "hsl(var(--color-base-background-950) / <alpha-value>)",
        },

        "base-inverted": {
          50: "hsl(var(--color-base-background-950) / <alpha-value>)",
          100: "hsl(var(--color-base-background-900) / <alpha-value>)",
          200: "hsl(var(--color-base-background-800) / <alpha-value>)",
          300: "hsl(var(--color-base-background-700) / <alpha-value>)",
          400: "hsl(var(--color-base-background-600) / <alpha-value>)",
          500: "hsl(var(--color-base-background-500) / <alpha-value>)",
          600: "hsl(var(--color-base-background-400) / <alpha-value>)",
          700: "hsl(var(--color-base-background-300) / <alpha-value>)",
          800: "hsl(var(--color-base-background-200) / <alpha-value>)",
          900: "hsl(var(--color-base-background-100) / <alpha-value>)",
          950: "hsl(var(--color-base-background-50) / <alpha-value>)",
        },
      },
      backgroundColor: {
        base: {
          50: "hsl(var(--color-base-background-50) / <alpha-value>)",
          100: "hsl(var(--color-base-background-100) / <alpha-value>)",
          200: "hsl(var(--color-base-background-200) / <alpha-value>)",
          300: "hsl(var(--color-base-background-300) / <alpha-value>)",
          400: "hsl(var(--color-base-background-400) / <alpha-value>)",
          500: "hsl(var(--color-base-background-500) / <alpha-value>)",
          600: "hsl(var(--color-base-background-600) / <alpha-value>)",
          700: "hsl(var(--color-base-background-700) / <alpha-value>)",
          800: "hsl(var(--color-base-background-800) / <alpha-value>)",
          900: "hsl(var(--color-base-background-900) / <alpha-value>)",
          950: "hsl(var(--color-base-background-950) / <alpha-value>)",
        },

        "base-inverted": {
          50: "hsl(var(--color-base-background-950) / <alpha-value>)",
          100: "hsl(var(--color-base-background-900) / <alpha-value>)",
          200: "hsl(var(--color-base-background-800) / <alpha-value>)",
          300: "hsl(var(--color-base-background-700) / <alpha-value>)",
          400: "hsl(var(--color-base-background-600) / <alpha-value>)",
          500: "hsl(var(--color-base-background-500) / <alpha-value>)",
          600: "hsl(var(--color-base-background-400) / <alpha-value>)",
          700: "hsl(var(--color-base-background-300) / <alpha-value>)",
          800: "hsl(var(--color-base-background-200) / <alpha-value>)",
          900: "hsl(var(--color-base-background-100) / <alpha-value>)",
          950: "hsl(var(--color-base-background-50) / <alpha-value>)",
        },
      },
      textColor: {
        base: {
          50: "hsl(var(--color-base-text-50) / <alpha-value>)",
          100: "hsl(var(--color-base-text-100) / <alpha-value>)",
          200: "hsl(var(--color-base-text-200) / <alpha-value>)",
          300: "hsl(var(--color-base-text-300) / <alpha-value>)",
          400: "hsl(var(--color-base-text-400) / <alpha-value>)",
          500: "hsl(var(--color-base-text-500) / <alpha-value>)",
          600: "hsl(var(--color-base-text-600) / <alpha-value>)",
          700: "hsl(var(--color-base-text-700) / <alpha-value>)",
          800: "hsl(var(--color-base-text-800) / <alpha-value>)",
          900: "hsl(var(--color-base-text-900) / <alpha-value>)",
          950: "hsl(var(--color-base-text-950) / <alpha-value>)",
        },
        "base-inverted": {
          50: "hsl(var(--color-base-text-950) / <alpha-value>)",
          100: "hsl(var(--color-base-text-900) / <alpha-value>)",
          200: "hsl(var(--color-base-text-800) / <alpha-value>)",
          300: "hsl(var(--color-base-text-700) / <alpha-value>)",
          400: "hsl(var(--color-base-text-600) / <alpha-value>)",
          500: "hsl(var(--color-base-text-500) / <alpha-value>)",
          600: "hsl(var(--color-base-text-400) / <alpha-value>)",
          700: "hsl(var(--color-base-text-300) / <alpha-value>)",
          800: "hsl(var(--color-base-text-200) / <alpha-value>)",
          900: "hsl(var(--color-base-text-100) / <alpha-value>)",
          950: "hsl(var(--color-base-text-50) / <alpha-value>)",
        },
      },
      gradientColorStops: {
        base: {
          50: "hsl(var(--color-base-background-50) / <alpha-value>)",
          100: "hsl(var(--color-base-background-100) / <alpha-value>)",
          200: "hsl(var(--color-base-background-200) / <alpha-value>)",
          300: "hsl(var(--color-base-background-300) / <alpha-value>)",
          400: "hsl(var(--color-base-background-400) / <alpha-value>)",
          500: "hsl(var(--color-base-background-500) / <alpha-value>)",
          600: "hsl(var(--color-base-background-600) / <alpha-value>)",
          700: "hsl(var(--color-base-background-700) / <alpha-value>)",
          800: "hsl(var(--color-base-background-800) / <alpha-value>)",
          900: "hsl(var(--color-base-background-900) / <alpha-value>)",
          950: "hsl(var(--color-base-background-950) / <alpha-value>)",
        },

        "base-inverted": {
          50: "hsl(var(--color-base-background-950) / <alpha-value>)",
          100: "hsl(var(--color-base-background-900) / <alpha-value>)",
          200: "hsl(var(--color-base-background-800) / <alpha-value>)",
          300: "hsl(var(--color-base-background-700) / <alpha-value>)",
          400: "hsl(var(--color-base-background-600) / <alpha-value>)",
          500: "hsl(var(--color-base-background-500) / <alpha-value>)",
          600: "hsl(var(--color-base-background-400) / <alpha-value>)",
          700: "hsl(var(--color-base-background-300) / <alpha-value>)",
          800: "hsl(var(--color-base-background-200) / <alpha-value>)",
          900: "hsl(var(--color-base-background-100) / <alpha-value>)",
          950: "hsl(var(--color-base-background-50) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [containerQueries, forms, typography],
};
